만국박람회 [STEP 2] John, Volga
2023newkrew/ios-exposition-universelle pull request #3
Opened 2023-01-10 06:22 UTC by limjae

@wonhee009 

안녕하세요 라자냐!
두번째 PR 이어서 보냅니다!🙏

## 고민한점

1. Deprecated method 지양
``` swift
   var content = cell.defaultContentConfiguration()
        content.image = UIImage(named: item.imageName)
        content.imageProperties.maximumSize.height = 70
        content.imageProperties.maximumSize.width = 70
        content.imageProperties.reservedLayoutSize.width = 70

        content.attributedText = NSMutableAttributedString(string: item.name)
            .applyFont(.title1)
        content.secondaryAttributedText = NSMutableAttributedString(string: item.shortDescription)
            .applyFont(.body)
        cell.contentConfiguration = content
```
- IOS 14.0 부터 Deprecated 된 method를 사용하지 않고자 위와 같은 방법으로 구현하였습니다.
- 이전 방법 : `cell.textLabel = ~~`, `cell.detailTextLabel = ~~`

2. 데이터 주입 방식
- ExpositionDetailsViewController에 필요한 데이터를 주입 할 때,
초기화 시점에 주입 하도록 구현하였습니다.

</br>

## 궁금한점
1. Subview 관리
- View 인스턴스 내에 subview들이 과도할 경우 (ex: Expo1900ViewController)
해당 인스턴스 내에서 subview들의 관리가 어려워 지는데,
이를 적절하게 해결 할 수 있는 방안이 있을까요?

2. 셀의 재활용성
``` swift
tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
```

- 이번 Table View에 활용한 셀은 기본 UICell을 재사용하여 구현했습니다.
하지만 이런 경우 재사용성에 기여가 되는지 궁금합니다.

2023-01-11 01:41 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요.

- 어떤 부분에서 "subview들의 관리가 어려워 지는데" 이렇게 느끼셨는지 궁금합니다. 단지 코드의 길이로 인해 작성자의 눈에 잘 안 들어와서 그러신거라면 코드로 뷰를 작성하다보면 UI와 관련된 코드들이 길어지는건 어쩔 수 없다고 생각합니다. 만약 subview가 동일한 뷰가 사용될 여지가 있다면 customView로써 따로 파일로 정의하고 사용하기도 합니다.
- 기본 cell의 사용과 재사용성과의 상관관계를 이해하지 못했습니다. 어떤 부분에서 재사용성에 도움이 될거라고 생각했는지 궁금합니다.

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/Extensions/String+Extension.swift
> +    }
String의 extension으로 정의해두면 모든 String에 대해서 `exposition`이라는 프로퍼티를 갖게될텐데요.
모든 String 타입이 해당 프로퍼티를 가져야 하나요?

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/Models/ExpositionItem.swift
> +    enum CodingKeys: String, CodingKey {
👍

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    private lazy var descriptionLabel = UILabel()
UI 프로퍼티들을 `lazy var`로 정의했는데 이유가 있나요?

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    private lazy var bottomTapStackView = {
tap 이라는 네이밍이 필요한가요?

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    }()
어떤 역할의 뷰/버튼인지가 네이밍에 드러나지 않는거 같습니다.
또한 뷰/버튼의 네이밍에 해당 UI의 위치는 없어도 될거 같습니다.

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +        applyData()
`viewWillAppear`에서 불러주는 이유가 있을까요?

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +        descriptionLabel.numberOfLines = 0
이런 부분들은 UI 프로퍼티를 init하는 시점에 지정해줄 수 없나요?

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/KoreanExpositionViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
`reuseIdentifier`를 `Cell` 보다는 어떤 셀인지 드러나는 identifier는 어떤가요?

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/KoreanExpositionViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
사용할 셀을 따로 정의하지 않고 기본 셀을 사용하기로 한건가요?

2023-01-11 01:41 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/ExpositionDetailsViewController.swift
> +    private let data: ExpositionItem?
옵셔널인 이유가 있을까요?
init으로 받는 파라미터는 non-optional인거 같아 질문드립니다.

2023-01-11 09:40 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    private lazy var descriptionLabel = UILabel()
보통 항상 필요한 View Instance를 넣을 때에 let을 사용하는데, 이 부분에서는 전체적으로 다 필요한 SubView들이기 때문에 View가 더 맞는것으로 생각이 듭니다.
추 후에 수정해서 반영하겠습니다. :)

2023-01-11 09:44 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +        descriptionLabel.numberOfLines = 0
말씀해주신 것 처럼, ViewController에 Instance 생성시에 추가하는 것이 조금 더 일관적인 작성법이라고 생각이 됩니다.

2023-01-11 09:46 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +        applyData()
viewWillAppear의 경우 화면이 나올 때 호출되는 함수 입니다.
사실 명세 자체에서는 json이 고정되어있고 data를 적용하는 부분을 viewDidLoad()에서만 해주어도 무방 하지만,
바뀔수도 있는 상황을 가정하고 생각해보면 viewWillAppear()에서 데이터를 로드해주는 것이 합당하다고 판단했습니다.

2023-01-11 09:47 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    }()
반영하겠습니다!!!@!

2023-01-11 09:47 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    private lazy var bottomTapStackView = {
불필요한 부분입니다.
네이밍 수정하여 다시 반영하겠습니다.

2023-01-11 09:49 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/ExpositionDetailsViewController.swift
> +    private let data: ExpositionItem?
이니셜라이저로 받아오는 파라미터를 변경하면서 수정했어야 했는데, 반영하지 못한 부분 같습니다...

2023-01-11 09:51 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/KoreanExpositionViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
CustomCell 을 생각해봤으나, 충분히 기본 Cell 만으로 명세에 나와있는 TableView Cell이 구현가능하다고 판단했습니다.
크게, Image와, LargeTitle, SecondaryTitle인데 이러한 요소가 기본 Cell이 프로퍼티로 가지고 있고 프로퍼티 속성도 변경이 가능한 부분이라 기본 셀을 사용하게 됐습니다.

2023-01-11 10:00 UTC, limjae commented on Expo1900/Expo1900/ViewControllers/KoreanExpositionViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
기본 cell의 사용과 재사용성과의 상관관계를 이해하지 못했습니다. 어떤 부분에서 재사용성에 도움이 될거라고 생각했는지 궁금합니다.
- 어디에 답변을 달아야 할지 몰라서 이곳에 답변드립니다.

기본 Cell을 사용하면 CustomCell보다 생성시에 드는 오버헤드 비용이 적을 것 같아서
dequeueReusableCell을 호출하는 것과 UITableViewCell을 초기화하여 사용하는것이
큰 차이를 만드는지 여부에 대해 궁금했었습니다.
이후에 추가적으로 고민해본 결과 오버헤드 비용 차이와 무관하게 dequeueReusableCell을 사용하면
생성 오버헤드 자체를 줄일 수 있어 등록하는 방향이 맞다고 생각했습니다!

2023-01-11 11:45 UTC, volgaHwang commented
@wonhee009 
안녕하세요! 라자냐!

john, volga 입니다.

STEP 2 PR 수정사항을 반영하여 노티드립니다!

## 변경사항
- `private lazy var` 키워드로 `subView` `Instance`를 선언해서 사용했었는데, 이번 만국박람회에서는 `lazy var` 키워드를 통해 렌더링이나 기타 부분에서 얻어낼 이득이 없다고 판단하여 해당 부분을 `private lazy var` -> `private let`으로 변경했습니다.
- 선언에 대한 일관성과 목적에 맞는 함수 사용을 위해, `subview`들에 대한 선언 속성 설정을 `instance` 초기화 과정에서 할 수 있도록 변경했습니다.
- 기존에 `String Extension`을 통해 `Title`을 가공했는데, 범위적인 부분으로 볼 때 제한적인 사용만을 목적으로 하는 해당 프로퍼티는 위치가 부적절하다고 판단하여, `Expo1900ViewController`에 옮겨두었습니다.
- `Expo1900ViewController`에 위치한 맨 밑의 `StackView`에 대해 `Tap`이라는 네이밍을 붙혀두었었는데 불필요하다고 판단하여 해당 부분을 지웠습니다.
    - 해당 `StackView`에 있는 `Flag`관련 `ImageView`와 `Button`에 대해 Renaming을 진행했고 반영했습니다.
- `TableViewCell`을 사용하는 곳에서 `Identifier`를 `Cell`로만 두었는데, 이 부분이 모호한 명칭이라 판단하여 `expoistionCell`로 네이밍을 진행했습니다.

## PR 관련 질의 응답

> 어떤 부분에서 "subview들의 관리가 어려워 지는데" 이렇게 느끼셨는지 궁금합니다. 단지 코드의 길이로 인해 작성자의 눈에 잘 안 들어와서 그러신거라면 코드로 뷰를 작성하다보면 UI와 관련된 코드들이 길어지는건 어쩔 수 없다고 생각합니다. 만약 subview가 동일한 뷰가 사용될 여지가 있다면 customView로써 따로 파일로 정의하고 사용하기도 합니다.

고민했던 부분이, 프로젝트 `Expo1900ViewController`를 보면 적지않은 `subvie` `instance`들이 보이는데, 이렇게 작은 구성만 하더라도 생각보다 많은 인스턴스가 생기는 것이 관리에 조금은 불편한 점이 아닐까 생각했습니다. 말씀 주신 대로 커스텀 뷰는 아직 공부가 더 필요한 부분인것 같은데, 한번 해보고 더 질문을 드려보겠습니다! :)

> 기본 cell의 사용과 재사용성과의 상관관계를 이해하지 못했습니다. 어떤 부분에서 재사용성에 도움이 될거라고 생각했는지 궁금합니다.

기본 cell의 사용과 재사용성과의 상관관계를 이해하지 못했습니다. 어떤 부분에서 재사용성에 도움이 될거라고 생각했는지 궁금합니다.

기본 Cell을 사용하면 CustomCell보다 생성시에 드는 오버헤드 비용이 적을 것 같아서
dequeueReusableCell을 호출하는 것과 UITableViewCell을 초기화하여 사용하는것 보다
큰 차이를 만드는지 여부에 대해 궁금했었습니다.
이후에 추가적으로 고민해본 결과 오버헤드 비용 차이와 무관하게 dequeueReusableCell을 사용하면
생성 오버헤드 자체를 줄일 수 있어 등록하는 방향이 맞다고 생각했습니다!

2023-01-11 12:00 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    }
https://github.com/2023newkrew/ios-exposition-universelle/pull/3#discussion_r1066491901 해당 코멘트를 보고 컴퓨티드 프로퍼티로 변경하신거 같은데요.
titleLabel의 text를 가지고 와서 조합해준뒤 다시 titleLabel.text로 지정해주는 부분이 어색한거 같습니다.
기존과 같이 String extension을 살리고 해당 VC에서만 접근 가능하도록 하는건 어떤가요?

``` swift
private extension String {
   var exposition
}
```
이런식으로요.

2023-01-11 12:00 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +        applyData()
json이 바뀔 수도 있는 상황이 어떤 상황인걸까요...? 또한 바뀐다고 해도 viewWillAppear에서 로드하는게 더 합당하다고 생각하는 이유가 궁금합니다.

2023-01-11 12:04 UTC, wonhee009 commented on Expo1900/Expo1900/ViewControllers/KoreanExpositionViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "Cell")
아하 네넵 우선 아시겠지만 dequeueReusableCell이 동작하는 방식이 큐에 몇개의 셀 인스턴스를 넣어두고 FIFO로 꺼내서 쓰는 방식여서 생성에 대한 이점도 있을테고 호출하는데 드는 오버헤드 비용은 크지 않을거 같습니다 :)

2023-01-11 12:22 UTC, volgaHwang commented on Expo1900/Expo1900/ViewControllers/Expo1900ViewController.swift
> +    }
몰랐던 방법인데.. 감사합니다... 이게되는군요 ㄱㅇㄴ....

2023-01-11 13:23 UTC, volgaHwang commented
@wonhee009 

안녕하세요 라자냐!
말씀해주신 `private extension String` 를 사용했습니다 ㅎㅎ

> json이 바뀔 수도 있는 상황이 어떤 상황인걸까요...? 또한 바뀐다고 해도 viewWillAppear에서 로드하는게 더 합당하다고 생각하는 이유가 궁금합니다.

말씀 주신 부분에 대해 답변을 하겠습니다!
해당 프로젝트에선 `json`파일을 로컬에서 읽어오고 `parsing`해서 사용 중인데, 다른 상황에서 `json` 데이터를 사용한다 라고 하는 것에 대해서는 `Networking` 상황에서 사용을 한다고 가정을 했습니다. (즉, 웹 서버에서 받아와서 쓰는 것을 가정했다는 뜻입니다!)

이 경우에 저희는 웹에서 받아오는 데이터가 잠시 `한국의 출품작 보러가기`버튼을 눌러서 다른 Scene을 갔다 오더라도 정적인 상태가 보증이 되는가에 대한 의문을 가졌습니다.
그렇기에, 잠시 화면을 옮겨가는 과정에서 업데이트된 데이터를 한번더 `parsing` 해서 화면에 뿌려주는 작업이 필요하다고 판단하였고 이러한 역할은 `viewWillApear()`에서 하는 것이 합당하다고 판단하여 해당 부분에 `loadJson()`, `applyData()`메소드를 넣게 된 것입니다!

2023-01-12 04:10 UTC, wonhee009 approved these changes

2023-01-12 04:10 UTC, merged