[ STEP2 & STEP3 ] forest, summer
2023newkrew/ios-exposition-universelle pull request #4
Opened 2023-01-12 04:21 UTC by shinhee-rebecca

@zdodev

안녕하세요, 소대!
STEP2를 구현하면서 오토레이아웃을 지정해버려서 STEP3까지 한번에 PR을 날리게 되었습니다.
양해 부탁드립니다 : )

[ 고민한 점 ]

1. Json 파일을 Struct로 디코딩하는 과정은 비즈니스 로직이므로 ViewController에 두기에는 적합하지 않다고 판단하였습니다. 그래서 해당 로직을 ExpositionService 클래스로 분리하였습니다.
2. Int+Extensions에서 decimal style의 NumberFormatter를 사용합니다. 그런데 NumberFormatter를 Int+Extension에서 초기화하여 사용하면 매번 사용할 때마다 NumberFormatter를 생성하는 비효율이 발생합니다. 그래서 NumberFormatter Extension을 만들어 사용하였습니다.

[ 질문 사항 ]

ViewController에 있는 IBAction과 IBOutlet도 외부에서 사용할 일이 없다고 판단하여서 private 접근지정자를 붙여두었습니다. 일반적으로 IBAction과 IBOutlet에도 private 접근지정자를 붙이는지 컨벤션이 궁금합니다.

2023-01-12 15:22 UTC, zdodev requested changes
안녕하세요! @shinhee-rebecca , @forestjae !

Step 3 까지 잘 구현해주셨습니다!
코드가 일성관있게 작성되어 읽기 수월했습니다!👍

다음 요구사항이 구현되어 있지 않은 것 같습니다.
- 첫 화면은 세로로만 볼 수 있도록 합니다
- 모든 화면에 Dynamic Type을 적용합니다(출품작 상세화면의 설명)

몇 가지 궁금증 남겨보았습니다!
확인 부탁드립니다!

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/Service/ExpositionService.swift
> +class ExpositionService {
상속을 하지 않는다면 `final` 키워드를 사용하는 것은 어떨까요?
`final` 키워드의 기능과 이점에 대해 알아보면 좋을 것 같습니다!

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/Service/ExpositionService.swift
> +    private init() { }
싱글턴 패턴으로 구현한 이유가 궁금합니다!

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/Service/ExpositionService.swift
> +    func fetchExpositionIntroductionData() -> Result<ExpositionIntroduction, DecodingError> {
`Result` 타입을 잘 활용해보셨네요.👍

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/Utils/DecodingError.swift
> +}
에러 타입을 잘 정의해보셨네요.👍

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/View/EntryDetailViewController.swift
> +    }()
뷰의 초기속성을 초기화할 때 설정해주셨네요.👍

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/View/EntryListViewController.swift
> +        entryDetailViewController.configureContent(with: items[indexPath.row])
뷰 컨트롤러간 데이터 전달 부분을 잘 구현해보셨네요.👍

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +
개행이 들어가 있습니다!

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/View/MainViewController.swift
> +    }
`EntryListViewController` 타입의 `configureContent` 메서드와 네이밍 컨벤션을 맞춰보는 것은 어떨까요?
불러오는 데이터만 다를 뿐 코드 구조는 비슷하여 네이밍도 맞추면 가독성이 더욱 좋아질 것 같습니다!

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/View/EntryListViewController.swift
> +        }
에러가 발생했을 때 `print` 로 처리하신 이유가 궁금합니다!

2023-01-12 15:22 UTC, zdodev commented on Expo1900/Expo1900/View/EntryListViewController.swift
> +        self.entryListTableView.dataSource = self
`Delegate`, `DataSource` 잘 구현해주셨네요.👍
지금처럼 `ViewController` 에서 구현할 수도 있지만 각각 분리해서 구현해보는 것은 어떨까요?
이 부분은 고민해보고 넘어가도 좋습니다!

2023-01-13 00:40 UTC, shinhee-rebecca commented on Expo1900/Expo1900/Service/ExpositionService.swift
> +class ExpositionService {
final 키워드의 기능과 이점을 확인했습니다. 적용하겠습니다 : )

2023-01-13 00:50 UTC, shinhee-rebecca commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +
수정하겠습니다. 감사합니다 : )

2023-01-13 00:51 UTC, shinhee-rebecca commented on Expo1900/Expo1900/View/MainViewController.swift
> +    }
MainViewController에는 cofigureObjects 상위의 configureContent 함수가 있습니다. 통일성 있는 코드를 위해 네이밍을 조금 더 고민해보겠습니다!

2023-01-13 01:08 UTC, shinhee-rebecca commented on Expo1900/Expo1900/Service/ExpositionService.swift
> +    private init() { }
고민해본 결과 동일한 context를 ExpositionDervice가 들고 있을 필요가 없고 필요한 부분에서 객체를 생성해도 무리가 없는 상황이라 싱글톤 패턴이 꼭 필요한 상황이 아니라서 변경하였습니다.

2023-01-13 01:14 UTC, shinhee-rebecca commented on Expo1900/Expo1900/View/MainViewController.swift
> +    }
확인후 수정완료했습니다! 감사합니다 : )

2023-01-13 01:17 UTC, forestjae commented on Expo1900/Expo1900/View/EntryListViewController.swift
> +        }
에러 처리와 관련하여, 특정한 요구사항이 없어 print만 해주는 방법으로 구현했습니다. 더 좋은 방법이 있을까요?

2023-01-13 01:21 UTC, forestjae commented on Expo1900/Expo1900/View/EntryListViewController.swift
> +        self.entryListTableView.dataSource = self
각각 분리해서 구현한다는게 어떤것인지 잘 이해하지 못했습니다. ViewController가 UITableViewDelegate와 UITableViewDataSource를 채택하지 않고 다른 객체에서 채택하는 것을 말씀하신걸까요?

2023-01-13 12:06 UTC, zdodev commented on Expo1900/Expo1900/View/EntryListViewController.swift
> +        }
사용자에게 더 좋은 경험을 제공해줄 수 있는 방법으로 구현했어도 좋을 것 같아서 코멘트 달아보았습니다!
관련 방안을 고민해보면 좋을 것 같습니다!

2023-01-13 12:08 UTC, zdodev commented on Expo1900/Expo1900/View/EntryListViewController.swift
> +        self.entryListTableView.dataSource = self
네, 맞습니다. `UITableViewDelegate` 역할과 `UITableViewDataSource` 역할을 다른 타입에게 넘기는 것에 대한 코멘트였습니다.

2023-01-13 12:12 UTC, zdodev approved these changes
안녕하세요. @shinhee-rebecca , @forestjae !

코멘트에 대한 의견 잘 보았습니다👍
피드백 반영된 부분도 확인하였습니다!

추가 코멘트에 대한 확인만하시면 될 것 같습니다!
Step 2 & 3 구현하시느라 고생하셨습니다!👍

2023-01-13 12:12 UTC, zdodev commented on Expo1900/Expo1900/View/MainViewController.swift
> +    }
좋습니다!👍

2023-01-13 12:12 UTC, merged